### ISSUE TITLE
LGTM.in is shutting down on 2018-10-01.

### ISSUE THREAD

**Issue by paveg** [leonhartX/danger-lgtm#11]
There is a sad news.

> LGTM.in is shutting down on 2018-10-01. I've been busy with a lot of things, and cannot spend time on this. The source is available on github.com/rahulsom/lgtmin and can be used to spin up a similar service. If you're interested in purchasing the domain and continuing to run this service, let me know, and we can work something out.

please, check this.

site: http://lgtm.in/

**Comment by leonhartX** [comment]
thanks, really sad news

**Comment by paveg** [comment]
I found another service https://www.lgtm.app/ .

**Comment by leonhartX** [comment]
Looks nice but seems it don't have an API. Maybe need to do some scraping.
And actually I don't have enough time to work on this for now, so if you can do this, that will be very  appreciated.

**Comment by paveg** [comment]
Sorry,  I haven't confirmation whether a public api exists.

> actually I don't have enough time to work on this for now

Okay.
I'll correspond if there is a room.

**Comment by af12066** [comment]
~~We may able to get random images from https://www.lgtm.app/g which is a similar URL in https://github.com/leonhartX/danger-lgtm/blob/master/lib/lgtm/plugin.rb#L22 .~~
sorry the above url returns a HTML response (not application/json)

**Comment by sleekybadger** [comment]
We can follow redirects to get image url without HTML parsing. See https://github.com/leonhartX/danger-lgtm/pull/12
